#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TNPA.Droid.Resource", IsApplication=true)]

namespace TNPA.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int banner = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int caidat = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contacts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FlashButton = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int gopy = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int hamburger = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int info = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int main = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int map = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int NoFlashButton = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pin = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int reminders = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int TakePhotoButton = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int thongke = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int todo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ToggleCameraButton = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tracuu = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int trogiup = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int xamarin = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int Image = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int List = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int Text = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int Text1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int Text2 = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int btnThemMoi = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int btnTraCuu = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int fragmentContainer = 2131034120;
			
			// aapt resource value: 0x7f050003
			public const int itButton = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int listView = 2131034112;
			
			// aapt resource value: 0x7f050009
			public const int tab_icon = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int tab_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int PageGopy = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PageHome = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PageItemLinhVuc = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PageMainTab = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PageTab = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PageThongKe = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PageTraCuu = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
